### PR TITLE
Update ru_ru.lang

### PR DESCRIPTION
**Pull request by Shellyoung**
Syntax error corrections. Added missing translation of config strings.

### CODE REVIEW

**Comment by stfwi** [comment]
Hi Shellyoung, thanks for PR, I'll pull it in for v1.0.11b1 (v1.0.10 is already in release testing).

**Comment by Shellyoung** [comment]
I couldn't find tooltip strings for configuration items in en_US lang file btw.

**Comment by stfwi** [comment]
Hi Shellyoung, there is now one small conflict after I pushed the release commit (exit sign translation). Could you take a quick look at this? Thx, cheers -

**Comment by Shellyoung** [comment]
Check it?

**Comment by stfwi** [comment]
Hi, looks good, can you quickly switch the target branch from master to develop? Thanks again!

**Comment by Shellyoung** [comment]
I'm new here. How can I do that?

**Comment by Shellyoung** [comment]
Done.

**Comment by Shellyoung** [comment]
You don't need it in master branch, right? So I close this one?

**Comment by stfwi** [comment]
Hi, ok, I have merged your other PR. Thx!

**Pull request closed without merging**
